## Deliverable 2. Create a Customer Travel Destinations Map.

In [21]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import weather_api_key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [22]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Omboue,GA,-1.5746,9.2618,81.19,82,100,7.11,light rain
1,1,Zhigansk,RU,66.7697,123.3711,-8.32,99,9,8.12,clear sky
2,2,Hodmezovasarhely,HU,46.4167,20.3333,72.18,39,7,12.01,clear sky
3,3,Punta Arenas,CL,-53.1500,-70.9167,42.91,56,0,16.11,clear sky
4,4,Albany,US,42.6001,-73.9662,48.94,70,100,1.99,overcast clouds

In [25]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 65
What is the maximum temperature you would like for your trip? 90

In [26]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Omboue,GA,-1.5746,9.2618,81.19,82,100,7.11,light rain
2,2,Hodmezovasarhely,HU,46.4167,20.3333,72.18,39,7,12.01,clear sky
5,5,Bonfim,BR,3.0833,-59.9500,86.36,47,98,7.11,overcast clouds
6,6,Puerto Ayora,EC,-0.7393,-90.3518,78.76,81,48,7.09,scattered clouds
7,7,Marsh Harbour,BS,26.5412,-77.0636,78.64,80,40,17.49,scattered clouds
9,9,Quatre Cocos,MU,-20.2078,57.7625,80.10,77,100,13.44,overcast clouds
11,11,Lorengau,PG,-2.0226,147.2712,80.64,84,96,15.19,overcast clouds
12,12,Sao Filipe,CV,14.8961,-24.4956,71.28,73,5,10.11,clear sky
13,13,Rikitea,PF,-23.1203,-134.9692,77.77,71,19,15.86,few clouds
19,19,Hithadhoo,MV,-0.6000,73.0833,83.34,64,8,3.00,clear sky

In [28]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                312
City                   312
Country                308
Lat                    312
Lng                    312
Max Temp               312
Humidity               312
Cloudiness             312
Wind Speed             312
Current Description    312
dtype: int64

In [29]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()
clean_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Omboue,GA,-1.5746,9.2618,81.19,82,100,7.11,light rain
2,2,Hodmezovasarhely,HU,46.4167,20.3333,72.18,39,7,12.01,clear sky
5,5,Bonfim,BR,3.0833,-59.9500,86.36,47,98,7.11,overcast clouds
6,6,Puerto Ayora,EC,-0.7393,-90.3518,78.76,81,48,7.09,scattered clouds
7,7,Marsh Harbour,BS,26.5412,-77.0636,78.64,80,40,17.49,scattered clouds
...,...,...,...,...,...,...,...,...,...,...
673,673,Buluang,PH,13.3068,123.3425,75.00,93,100,3.53,overcast clouds
675,675,Santiago,CL,-33.4569,-70.6483,79.29,36,0,2.30,clear sky
676,676,Myitkyina,MM,25.3833,97.4000,72.09,66,43,4.36,scattered clouds
677,677,Denpasar,ID,-8.6500,115.2167,80.26,94,40,2.30,scattered clouds
679,679,Manado,ID,1.4870,124.8455,77.77,94,40,1.14,scattered clouds

In [30]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Omboue,GA,81.19,light rain,-1.5746,9.2618,
2,Hodmezovasarhely,HU,72.18,clear sky,46.4167,20.3333,
5,Bonfim,BR,86.36,overcast clouds,3.0833,-59.9500,
6,Puerto Ayora,EC,78.76,scattered clouds,-0.7393,-90.3518,
7,Marsh Harbour,BS,78.64,scattered clouds,26.5412,-77.0636,
9,Quatre Cocos,MU,80.10,overcast clouds,-20.2078,57.7625,
11,Lorengau,PG,80.64,overcast clouds,-2.0226,147.2712,
12,Sao Filipe,CV,71.28,clear sky,14.8961,-24.4956,
13,Rikitea,PF,77.77,few clouds,-23.1203,-134.9692,
19,Hithadhoo,MV,83.34,clear sky,-0.6000,73.0833,

In [31]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame

        lat = row["Lat"]
        lng = row["Lng"]
        params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
        base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
        hotels = requests.get(base_url, params=params).json()   
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
        try:
            hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        except (IndexError):
            print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [33]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna()
clean_hotel_df = clean_hotel_df[clean_hotel_df["Hotel Name"] != ""]
clean_hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Omboue,GA,81.19,light rain,-1.5746,9.2618,Hotel Olako
2,Hodmezovasarhely,HU,72.18,clear sky,46.4167,20.3333,Hotel Fama
6,Puerto Ayora,EC,78.76,scattered clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel
7,Marsh Harbour,BS,78.64,scattered clouds,26.5412,-77.0636,Abaco Beach Resort
9,Quatre Cocos,MU,80.10,overcast clouds,-20.2078,57.7625,Sunrise Attitude Hotel
11,Lorengau,PG,80.64,overcast clouds,-2.0226,147.2712,Lorengau Harbourside Hotel
12,Sao Filipe,CV,71.28,clear sky,14.8961,-24.4956,Hotel Xaguate
13,Rikitea,PF,77.77,few clouds,-23.1203,-134.9692,People ThankYou
19,Hithadhoo,MV,83.34,clear sky,-0.6000,73.0833,Scoop Guest House
20,Atuona,PF,77.90,light rain,-9.8000,-139.0333,Villa Enata

In [34]:
# 8a. Create the output File (CSV)
output_data_file = '../Vacation_Search/WeatherPy_vacation.csv'
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [35]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description}</dd> and <dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [36]:
# 11a. Add a marker layer for each city to the map. 
max_temp = clean_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))